# Section 1: Imports, Functions, and Constants

In [1]:
# Library Import Statements

import pandas as pd
import numpy as np
from sklearn.preprocessing import normalize


In [2]:
def euclidean_dist_calc(test, train):
    """
    Compute the Euclidean distance between each
    point in test and all points in train.
    """
    num_test = test.shape[0]
    num_train = train.shape[0]
    dists = np.zeros((num_test, num_train)) 
    sum_squares_train = np.sum(np.square(train), axis=1)
    sum_squares_test = np.sum(np.square(test), axis=1)
    sum_combo = np.dot(test, train.T) * -2
    dists = np.sqrt(((sum_combo + sum_squares_train).T + sum_squares_test).T)
    return dists

In [3]:
def manhattan_dist_calc(test, train):
    """
    Compute the Manhattan distance between each
    point in test and all points in train.
    """
    num_test = test.shape[0]
    num_train = train.shape[0]
    dists = np.zeros((num_test, num_train)) 
    for i in range(num_test):
        test_point = test[i]
        result_matrix = train - test_point
        result_matrix = np.absolute(result_matrix)
        result_vector = np.sum(result_matrix, axis=1)
        dists[i] = result_vector
    return dists

In [4]:
def compute_distances(test, train, metric):
    """
    Computes distances according to either 
    Euclidean or Manhattan distance metrics given
    a test set and a training set.
    
    The input metric must either be "Euclidean" or 
    "Manhattan".
    """
    if metric == "Euclidean":
        dists = euclidean_dist_calc(test, train)
    elif metric == "Manhattan":
        dists = manhattan_dist_calc(test, train)
    else:
        raise ValueError("Invalid value d% for metric; must be Euclidean or Manhattan as a string." % metric)
    return dists

In [5]:
k = 45

In [7]:
# Convert Class labels to numbers
# 0 = stable
# 1 = unstable


data.loc[(data['stabf'] == 'stable'), 'stabf'] = 0
data.loc[(data['stabf'] == 'unstable'), 'stabf'] = 1
data['stabf'] = pd.to_numeric(data['stabf'])
data['stabf']

0       1
1       0
2       1
3       1
4       1
       ..
4995    1
4996    1
4997    0
4998    1
4999    0
Name: stabf, Length: 5000, dtype: int64

In [8]:
# Split dataframe into testing and training sets
train_data = data.iloc[:3500]
test_data = data.iloc[3500:]
test_data

tau1      tau2      tau3      tau4        p1        p2        p3  \
3500  7.592223  1.389509  7.285896  6.031028  4.901480 -1.809328 -1.536639   
3501  9.203739  3.031134  2.742088  7.318112  4.379546 -1.160296 -1.374819   
3502  4.016004  8.501127  5.345373  6.943443  2.952986 -0.535994 -1.375817   
3503  1.568860  2.338635  7.562933  0.931341  3.180046 -1.887828 -0.673774   
3504  8.906023  4.356134  4.086695  1.396348  4.998403 -1.232689 -1.910843   
...        ...       ...       ...       ...       ...       ...       ...   
4995  3.592940  8.130493  3.270724  8.075292  4.772430 -1.458529 -1.690274   
4996  7.656651  6.411748  5.655960  6.045712  3.193900 -0.918944 -1.377013   
4997  1.069438  6.581439  1.230892  9.937483  3.756828 -1.524720 -0.516322   
4998  4.629745  8.353612  8.119304  8.600847  2.960941 -1.424327 -0.890685   
4999  0.754512  9.723392  9.264871  1.415836  5.029876 -1.281568 -1.946921   

            p4        g1        g2        g3        g4      stab  stabf  
3500 -1.555512  0.444016  0.469558  0.559769  0.170529  0.001593      1  
3501 -1.844431  0.322139  0.945597  0.786776  0.527852  0.015995      1  
3502 -1.041175  0.662382  0.300356  0.251775  0.559976  0.027832      1  
3503 -0.618444  0.321079  0.081876  0.298656  0.078052 -0.051548      0  
3504 -1.854870  0.143437  0.556369  0.929642  0.686855  0.007881      1  
...        ...       ...       ...       ...       ...       ...    ...  
4995 -1.623627  0.210123  0.683625  0.159779  0.344948  0.011499      1  
4996 -0.897943  0.443617  0.490799  0.988511  0.788984  0.086436      1  
4997 -1.715786  0.501101  0.381437  0.773236  0.822149 -0.025390      0  
4998 -0.645929  0.383265  0.241701  0.609101  0.756135  0.052382      1  
4999 -1.801387  0.448670  0.413843  0.273108  0.251181 -0.036986      0  

[1500 rows x 14 columns]

# Section 3: Split Labels from Train & Test Sets, Numpyize Them

In [9]:
# Save labels for train and test sets
train_labels = train_data['stabf'].to_numpy()
test_labels = test_data['stabf'].to_numpy()
test_labels

array([1, 1, 1, ..., 0, 1, 0], dtype=int64)

# Section 2: Make Train & Test Sets

In [6]:
# Data Import Cell
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv"
data = pd.read_csv(url, sep=",")
data = data.head(5000)
data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [10]:
# Drop class column from train and test sets
train = train_data.drop('stabf', axis=1)
test = test_data.drop('stabf', axis=1)
test

tau1      tau2      tau3      tau4        p1        p2        p3  \
3500  7.592223  1.389509  7.285896  6.031028  4.901480 -1.809328 -1.536639   
3501  9.203739  3.031134  2.742088  7.318112  4.379546 -1.160296 -1.374819   
3502  4.016004  8.501127  5.345373  6.943443  2.952986 -0.535994 -1.375817   
3503  1.568860  2.338635  7.562933  0.931341  3.180046 -1.887828 -0.673774   
3504  8.906023  4.356134  4.086695  1.396348  4.998403 -1.232689 -1.910843   
...        ...       ...       ...       ...       ...       ...       ...   
4995  3.592940  8.130493  3.270724  8.075292  4.772430 -1.458529 -1.690274   
4996  7.656651  6.411748  5.655960  6.045712  3.193900 -0.918944 -1.377013   
4997  1.069438  6.581439  1.230892  9.937483  3.756828 -1.524720 -0.516322   
4998  4.629745  8.353612  8.119304  8.600847  2.960941 -1.424327 -0.890685   
4999  0.754512  9.723392  9.264871  1.415836  5.029876 -1.281568 -1.946921   

            p4        g1        g2        g3        g4      stab  
3500 -1.555512  0.444016  0.469558  0.559769  0.170529  0.001593  
3501 -1.844431  0.322139  0.945597  0.786776  0.527852  0.015995  
3502 -1.041175  0.662382  0.300356  0.251775  0.559976  0.027832  
3503 -0.618444  0.321079  0.081876  0.298656  0.078052 -0.051548  
3504 -1.854870  0.143437  0.556369  0.929642  0.686855  0.007881  
...        ...       ...       ...       ...       ...       ...  
4995 -1.623627  0.210123  0.683625  0.159779  0.344948  0.011499  
4996 -0.897943  0.443617  0.490799  0.988511  0.788984  0.086436  
4997 -1.715786  0.501101  0.381437  0.773236  0.822149 -0.025390  
4998 -0.645929  0.383265  0.241701  0.609101  0.756135  0.052382  
4999 -1.801387  0.448670  0.413843  0.273108  0.251181 -0.036986  

[1500 rows x 13 columns]

In [11]:
# Convert train and test to numpy arrays
train = train.to_numpy()
test = test.to_numpy()
test

array([[ 7.59222336e+00,  1.38950867e+00,  7.28589559e+00, ...,
         5.59768619e-01,  1.70528709e-01,  1.59300624e-03],
       [ 9.20373904e+00,  3.03113388e+00,  2.74208849e+00, ...,
         7.86776143e-01,  5.27851948e-01,  1.59949946e-02],
       [ 4.01600415e+00,  8.50112731e+00,  5.34537329e+00, ...,
         2.51774855e-01,  5.59975960e-01,  2.78322527e-02],
       ...,
       [ 1.06943762e+00,  6.58143888e+00,  1.23089213e+00, ...,
         7.73236128e-01,  8.22149435e-01, -2.53904805e-02],
       [ 4.62974535e+00,  8.35361207e+00,  8.11930402e+00, ...,
         6.09100855e-01,  7.56135124e-01,  5.23822770e-02],
       [ 7.54511861e-01,  9.72339201e+00,  9.26487092e+00, ...,
         2.73108030e-01,  2.51180820e-01, -3.69859336e-02]])

# Section 4: Analysis

In [13]:
# Compute Distance Matrix

dists = compute_distances(test, train, "Euclidean")
#dists = compute_distances(test, train, "Manhattan")
dists

array([[0.0529621 , 0.04462797, 0.05458674, ..., 0.06326677, 0.05746328,
        0.04569973],
       [0.04906884, 0.04705974, 0.05646954, ..., 0.06194467, 0.05296708,
        0.05821566],
       [0.03821409, 0.05069847, 0.05365513, ..., 0.0557102 , 0.0613269 ,
        0.053487  ],
       ...,
       [0.05835539, 0.05998833, 0.06828727, ..., 0.0537749 , 0.04646163,
        0.06121794],
       [0.04297523, 0.06438266, 0.06614503, ..., 0.06783632, 0.07152282,
        0.0638074 ],
       [0.07608597, 0.06118565, 0.06595964, ..., 0.06664703, 0.07698337,
        0.07384184]])

In [12]:
# normalize the datasets
train = normalize(train, axis=0)
test = normalize(test, axis=0)
test

array([[ 0.03294783,  0.0059878 ,  0.03189501, ...,  0.02445562,
         0.00752012,  0.00101395],
       [ 0.03994129,  0.01306203,  0.01200387, ...,  0.03437331,
         0.02327766,  0.01018084],
       [ 0.01742818,  0.03663382,  0.02340011, ...,  0.01099974,
         0.02469429,  0.01771527],
       ...,
       [ 0.00464102,  0.02836133,  0.0053884 , ...,  0.03378176,
         0.03625584, -0.01616108],
       [ 0.02009162,  0.03599814,  0.03554337, ...,  0.02661089,
         0.03334468,  0.03334139],
       [ 0.00327434,  0.04190091,  0.04055825, ...,  0.01193176,
         0.01107678, -0.0235416 ]])

In [14]:
# Make Predictions

num_test = dists.shape[0]
y_pred = np.zeros(num_test)
for i in range(num_test):
    nearest_neighbors_indices = np.argsort(dists[i])
    closest_y = np.zeros(k)
    for m in range(k):
        closest_y[m] = train_labels[nearest_neighbors_indices[m]]
    labels = []
    label_counts = []
    for label in closest_y:
        if label not in labels:
          labels.append(label)
          label_counts.append(1)
        else:
          label_counts[labels.index(label)] = label_counts[labels.index(label)] + 1
    mode_labels = np.argsort(label_counts)[::-1]
    y_pred[i] = labels[mode_labels[0]]
y_pred

array([1., 1., 1., ..., 0., 1., 0.])

In [15]:
# Compute and print the fraction of correctly predicted examples
num_correct = np.sum(y_pred == test_labels)
accuracy = float(num_correct) / num_test
print('Got %d / %d correct => accuracy: %f' % (num_correct, num_test, accuracy))

Got 1402 / 1500 correct => accuracy: 0.934667


# Section 5: Reminders and Task Description

## DOs
- DO Run the k-value cell in Section 1 and the cells in Section 4 individually to test each parameter set (k-value and distance metric).
- DO Edit the cell for k-value in Section 1.
- DO Edit the cell that calculates the distances using one of two distance metrics in Section 4.
- DO Take Notes on paper.

## DO NOTs
- DO NOT Run All.
- DO NOT Edit any cells other than the two specified.
- DO NOT Move cells.
- DO NOT Delete cells.
- DO NOT Add cells.
- DO NOT Take Notes in the notebook.

## Task Description Reminder
You are tasked with tuning the parameters for k-value and distance metric to find the best k-value for each distance metric and then to determine which distance metric, with its optimal k-value, results in the highest accuracy (most accurate model). To do this, you will have to evaluate each combination.

## Lorem Ipsum
Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipiscing velit, sed quia non numquam do eius modi tempora incididunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrumd exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? DQuis autem vel eum irure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.

# Irrelevant Text
This is more irrelevant text padding the notebook. Don't read this any further. It's pointless. Why are you still reading this? Focus on the task at hand.